version: "3.8"

services:
  plex:
    image: plexinc/pms-docker
    container_name: plex-server
    restart: on-failure
    volumes:
      - e:/docker/media/plex/config:/config
      - e:/docker/media/plex/transcode:/transcode
      - e:/docker/media/plex/media:/media
    environment:
      - "TZ=Europe/Stockholm"
      - "PLEX_CLAIM=claim-_nxFhTDtyFUeLaLhCE9z"
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.entrypoints=insecure"
      - "traefik.http.routers.plex.rule=Host(`plex.localhost`)"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    volumes:
      - e:/docker/media/transmission/config:/config
      - e:/docker/media/transmission/watch:/watch
      - e:/docker/media/plex/media/movies:/downloads
    ports:
      - "9091:9091"
    networks:
      - proxy
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Etc/UTC"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.torrent.entrypoints=insecure"
      - "traefik.http.routers.torrent.rule=Host(`torrent.localhost`)"
      - "traefik.http.services.torrent.loadbalancer.server.port=9091"
      # - "traefik.http.routers.adguardhome.tls.certresolver=le"

networks:
  traefik-network:
    external: true
